exports.JOB_STATUS = {
    PENDING: "pending",
    INTERVIEW: "interview",
    DECLINED: "declined",
};

exports.JOB_TYPE = {
    HIGHER_STUDIES: "Higher Studies",
    PLACEMENT: "Placement",
    ENTREPRENEURSHIP: "Entrepreneurship",
};

exports.JOB_SORT_BY = {
    NEWEST_FIRST: "newest",
    OLDEST_FIRST: "oldest",
    ASCENDING: "a-z",
    DESCENDING: "z-a",
};

exports.PROJECT_DOMAIN = {
    INDUSTRY_PROJECTS: "Industry Projects",
    RESEARCH_PROJECTS: "Research Projects",
    HEALTH_AND_FAMILY_WELFARE: "Health & Family Welfare",
    EDUCATION_AND_HUMAN_RESOURCE_DEVELOPMENT: "Education and Human Resource Development",
    WATER_RESOURCES_AND_SANITATION: "Water Resources and Sanitation",
    AGRICULTURE: "Agriculture",
    ENVIRONMENT_AND_FORESTS: "Environment & Forests",
    INFRASTRUCTURE: "Infrastructure ",
    COMMERCE_AND_INDUSTRY: "Commerce & Industry",
    SCIENCE_AND_TECHNOLOGY: "Science & Technology",
    RENEWABLE_ENERGY: "Renewable Energy",
    RURAL_DEVELOPMENT: "Rural Development",
    FINANCE: "Finance",
    EXTERNAL_AFFAIRS: "External Affairs",
    DEFENCE: "Defence",
    LABOUR_AND_EMPLOYMENT: "Labour & Employment",
    MINORITY_AFFAIRS: "Minority Affairs",
    TRIBAL_AFFAIRS: "Tribal Affairs",
    SOCIAL_JUSTICE_AND_EMPOWERMENT: "Social Justice & Empowerment",
    WOMEN_AND_CHILD_DEVELOPMENT: "Women & Child Development",
    YOUTH_AFFAIRS_AND_SPORTS: "Youth Affairs & Sports",
    HOME_AFFAIRS: "Home Affairs",
    PETROLEUM_AND_NATURAL_GAS: "Petroleum & Natural Gas",
    POWER: "Power",
    MICRO_SMALL_AND_MEDIUM_ENTERPRISES: "Micro, Small and Medium Enterprises",
    FOOD_PROCESSING_INDUSTRIES: "Food Processing Industries",
    TEXTILES: "Textiles",
    INFORMATION_AND_BROADCASTING: "Information & Broadcasting",
    LAW_AND_JUSTICE: "Law & Justice",
    CORPORATE_AFFAIRS: "Corporate Affairs",
    CHEMICALS_AND_FERTILIZERS: "Chemicals & Fertilizers",
    HEAVY_INDUSTRY_AND_PUBLIC_ENTERPRISES: "Heavy Industry & Public Enterprises",
    MINES: "Mines",
    HOUSING_AND_URBAN_POVERTY_ALLEVIATION: "Housing & Urban Poverty Alleviation",
    TOURISM: "Tourism",
    COAL: "Coal",
    PANCHAYATI_RAJ: "Panchayati Raj",
    PARLIAMENTARY_AFFAIRS: "Parliamentary Affairs",
    PERSONNEL_PUBLIC_GRIEVANCES_AND_PENSIONS: "Personnel, Public Grievances & Pensions",
    SHIPPING: "Shipping",
    STATISTICS_AND_PROGRAMME_IMPLEMENTATION: "Statistics & Programme Implementation",
    STEEL: "Steel",
    CIVIL_AVIATION: "Civil Aviation",
    PLANNING_COMMISSION: "Planning Commission",
    ATOMIC_ENERGY: "Atomic Energy",
    SPACE: "Space",
    DEVELOPMENT_OF_NORTH_EASTERN_REGION: "Development of North Eastern Region",
    CULTURE: "Culture",
    EARTH_SCIENCES: "Earth Sciences",
    OTHEERS: "Others",
};
